### ISSUE TITLE
Error retrieving userID.

### ISSUE THREAD

**Issue by TypicalShavonne** [roxtigger2003/Sumi-chan-bot#1]
Login từ nơi khác mặc dù mình chạy trên máy mình đã login sẵn fb trên web r ;-; 

> 'Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.'

**Comment by roxtigger2003** [comment]
ông thử tắt cái userAgent trong login.js rồi thử lại xem ông
