### ISSUE TITLE
Bot không hoạt động

### ISSUE THREAD

**Issue by ElsChaos** [roxtigger2003/Sumi-chan-bot#2]
Bot liên tục spam đăng nhập rồi lại bị out rồi đăng nhập, làm đúng hết các bước. npm start thì lại bị.
![image](https://user-images.githubusercontent.com/51498641/80680323-bdd32a80-8ae8-11ea-9a50-d730ff1bca3a.png)

**Comment by roxtigger2003** [comment]
sorry ông vì cái telegram nó không báo cái issues này. bây giờ ông giúp tui tạo 1 file tên là groupID.json tại app/handle/src và bên trong đấy ông để là [] nha

**Comment by roxtigger2003** [comment]
hmmm ông xem lại xem?
